"""add training scheduler

Revision ID: 7b1f53348829
Revises: 9a98bd885386
Create Date: 2026-09-18 12:38:57.451487
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "7b1f53348829"
down_revision: Union[str, None] = "9a98bd885386"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gpu_devices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("uuid", sa.String(length=120), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column(
            "model",
            sa.Enum("ANY", "RTX_3090", "RTX_4090", name="gpumodelpolicy", native_enum=False),
            nullable=False,
        ),
        sa.Column("memory_gb", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("index"),
    )
    op.create_index(op.f("ix_gpu_devices_uuid"), "gpu_devices", ["uuid"], unique=True)
    op.create_table(
        "runtime_images",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=False),
        sa.Column("digest", sa.String(length=255), nullable=False),
        sa.Column("framework", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "training_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("default_runtime_image_id", sa.String(length=36), nullable=False),
        sa.Column("parameter_schema", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_runtime_image_id"],
            ["runtime_images.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "training_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=False),
        sa.Column("code_version_id", sa.String(length=36), nullable=False),
        sa.Column("runtime_image_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "QUEUED",
                "PREPARING",
                "STARTING",
                "RUNNING",
                "CANCEL_REQUESTED",
                "STOPPING",
                "STOPPED",
                "SUCCEEDED",
                "FAILED",
                name="trainingrunstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("command", sa.JSON(), nullable=False),
        sa.Column("requested_gpu_count", sa.Integer(), nullable=False),
        sa.Column(
            "requested_gpu_model",
            sa.Enum("ANY", "RTX_3090", "RTX_4090", name="gpumodelpolicy", native_enum=False),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.String(length=255), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["code_version_id"],
            ["code_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["runtime_image_id"],
            ["runtime_images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["training_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_training_runs_status"), "training_runs", ["status"], unique=False)
    op.create_table(
        "gpu_allocations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("gpu_device_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["gpu_device_id"],
            ["gpu_devices.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["training_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gpu_device_id", name="uq_active_gpu_allocation"),
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["training_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_events")
    op.drop_table("gpu_allocations")
    op.drop_index(op.f("ix_training_runs_status"), table_name="training_runs")
    op.drop_table("training_runs")
    op.drop_table("training_templates")
    op.drop_table("runtime_images")
    op.drop_index(op.f("ix_gpu_devices_uuid"), table_name="gpu_devices")
    op.drop_table("gpu_devices")
    # ### end Alembic commands ###
